"""Bit-exact verification: native WASM vs. specialized transformer.

Gate 1 of the PSL verification chain. For each primitive in primitives/, this
test:

1. Loads N randomized witnesses (from tests/vectors/<name>.json, generated by
   tools/gen_vectors.py).
2. For each witness, builds the universal-model input file (program prefix +
   input bytes) and runs it through the graph evaluator (`wasm-eval`).
3. Builds the specialized-model input file (start + input bytes) and runs it
   through the specialized model (`wasm-run` against weights/<name>.bin).
4. Asserts the predicted token sequences are byte-for-byte identical.

Usage:
    uv run pytest tests/test_bit_exact.py -v              # 100/primitive (quick)
    uv run pytest tests/test_bit_exact.py -v --full       # 10k/primitive

Failures are dumped to tests/failures/<primitive>_<hash>.txt.
"""

import hashlib
import json
import os
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
TVM = Path(os.environ.get("TRANSFORMER_VM_PATH", "/mnt/c/Users/atchi/Transformer-VM"))
DATA_DIR = REPO_ROOT / "data"
WEIGHTS_DIR = REPO_ROOT / "weights"
VECTORS_DIR = REPO_ROOT / "tests" / "vectors"
FAILURES_DIR = REPO_ROOT / "tests" / "failures"

PRIMITIVES = [
    "ledger_freeze",
    "ledger_transfer",
    "ledger_mint",
    "ledger_burn",
    "ledger_multi_asset",
    "mpt_apply_delta",
]


def _ensure_primitive_artifacts(primitive: str):
    """Skip a single test if its primitive's artifacts aren't built."""
    venv = TVM / ".venv"
    if not venv.exists():
        pytest.skip(
            f"Transformer-VM venv not synced at {venv}; run `cd {TVM} && uv sync`"
        )
    if not (DATA_DIR / f"{primitive}.txt").exists():
        pytest.skip(
            f"data/{primitive}.txt missing; run `./tools/compile.sh primitives/{primitive}.c --args ...`"
        )
    if not (WEIGHTS_DIR / f"{primitive}.bin").exists():
        pytest.skip(
            f"weights/{primitive}.bin missing; run `./tools/specialize.sh data/{primitive}.txt`"
        )


def load_vectors(primitive: str, limit: int | None) -> list[dict]:
    path = VECTORS_DIR / f"{primitive}.json"
    if not path.exists():
        pytest.skip(f"{path} missing; run `python tools/gen_vectors.py`")
    with path.open() as f:
        data = json.load(f)
    vecs = data["vectors"]
    return vecs if limit is None else vecs[:limit]


def split_program_and_input(txt: str) -> tuple[list[str], list[str]]:
    """Split a universal .txt into (program_tokens, sample_input_tokens)."""
    tokens = txt.split()
    end = tokens.index("}")
    return tokens[: end + 1], tokens[end + 1 :]


def split_spec_and_input(txt: str) -> tuple[list[str], list[str]]:
    """Split a _spec.txt into ([start], sample_input_tokens)."""
    tokens = txt.split()
    return tokens[:1], tokens[1:]


def render_input_tokens(input_values: list[int]) -> list[str]:
    """Encode a witness as Transformer-VM input tokens.

    The witness is a list of decimal byte values (e.g. [1, 0, 0, ..., 0]).
    These are joined by spaces into an ASCII string ("1 0 0 0..."), then
    NUL-terminated, then each byte is tokenized: printable ASCII becomes the
    literal char, otherwise 2-char hex. Matches `compile_wasm.format_input_section`.
    A trailing `commit(+0,sts=0,bt=0)` token signals end-of-input.
    """
    text = " ".join(str(b) for b in input_values)
    data = text.encode("utf-8") + b"\x00"
    tokens = []
    for b in data:
        if 0x20 < b < 0x7F and chr(b) not in ("{", "}"):
            tokens.append(chr(b))
        else:
            tokens.append(f"{b:02x}")
    tokens.append("commit(+0,sts=0,bt=0)")
    return tokens


def run_wasm_eval(input_file: Path) -> list[str]:
    cmd = ["uv", "run", "wasm-eval", str(input_file), "--nohull"]
    result = subprocess.run(
        cmd, cwd=str(TVM), capture_output=True, text=True, timeout=120
    )
    if result.returncode != 0:
        raise RuntimeError(f"wasm-eval failed: {result.stderr}")
    # wasm-eval prints PASS/FAIL on stderr; the predicted tokens go through
    # _verbose flag. We re-run via Python API for actual token capture.
    raise NotImplementedError("subprocess capture not implemented; use python_run")


def python_run_universal(program_file: Path, sample_input_tokens: list[str], witness_tokens: list[str]) -> list[str]:
    """Run the universal graph evaluator with our witness in place of the sample input."""
    import sys
    sys.path.insert(0, str(TVM))
    from transformer_vm.evaluator import Runtime

    rt = Runtime(use_hull=False)
    program_tokens, _ = split_program_and_input(program_file.read_text())

    full_input = program_tokens + witness_tokens
    vals = None
    for tok in full_input:
        vals = rt.step(tok)

    predicted = list(full_input)
    max_steps = 50000
    for _ in range(max_steps):
        next_tok = rt.predict_next(vals)
        predicted.append(next_tok)
        if next_tok == "halt":
            break
        vals = rt.step(next_tok)

    rt.destroy()
    return predicted


def python_run_specialized(weights_file: Path, witness_tokens: list[str]) -> list[str]:
    """Run the specialized model (StandardKVCache) on start + witness."""
    import sys
    sys.path.insert(0, str(TVM))
    import torch
    from transformer_vm.attention.standard_cache import StandardKVCache
    from transformer_vm.model.weights import load_weights

    model, all_tokens, tok_to_idx = load_weights(str(weights_file))
    seq = ["start"] + witness_tokens
    idx_seq = [tok_to_idx[t] for t in seq]
    result = model.generate_with_cache(
        torch.tensor([idx_seq], dtype=torch.long),
        max_new_tokens=50000,
        cache_class=StandardKVCache,
    )
    return [all_tokens[i] for i in result[0].tolist()]


def strip_universal_program_prefix(tokens: list[str]) -> list[str]:
    end = tokens.index("}")
    return tokens[end + 1 :]


def strip_specialized_start(tokens: list[str]) -> list[str]:
    if tokens and tokens[0] == "start":
        return tokens[1:]
    return tokens


def dump_failure(primitive: str, witness: dict, universal: list[str], specialized: list[str]):
    FAILURES_DIR.mkdir(parents=True, exist_ok=True)
    h = hashlib.blake2b(json.dumps(witness, sort_keys=True).encode(), digest_size=8).hexdigest()
    out = FAILURES_DIR / f"{primitive}_{h}.txt"
    with out.open("w") as f:
        f.write(f"# Bit-exact mismatch for {primitive}\n")
        f.write(f"witness = {json.dumps(witness)}\n\n")
        f.write(f"universal ({len(universal)} tokens):\n")
        f.write(" ".join(universal) + "\n\n")
        f.write(f"specialized ({len(specialized)} tokens):\n")
        f.write(" ".join(specialized) + "\n\n")
        for i, (u, s) in enumerate(zip(universal, specialized)):
            if u != s:
                f.write(f"first mismatch at index {i}: universal='{u}' specialized='{s}'\n")
                break


@pytest.mark.parametrize("primitive", PRIMITIVES)
def test_primitive_bit_exact(primitive, vector_count):
    _ensure_primitive_artifacts(primitive)
    program_file = DATA_DIR / f"{primitive}.txt"
    weights_file = WEIGHTS_DIR / f"{primitive}.bin"

    vectors = load_vectors(primitive, vector_count)
    failed = 0
    for v in vectors:
        witness_tokens = render_input_tokens(v["input"])

        universal_tokens = python_run_universal(program_file, [], witness_tokens)
        specialized_tokens = python_run_specialized(weights_file, witness_tokens)

        u_exec = strip_universal_program_prefix(universal_tokens)
        s_exec = strip_specialized_start(specialized_tokens)

        if u_exec != s_exec:
            failed += 1
            dump_failure(primitive, v, u_exec, s_exec)
            if failed <= 3:
                print(f"[bit_exact] {primitive} mismatch on witness {v}")

    assert failed == 0, f"{primitive}: {failed}/{len(vectors)} mismatches (see tests/failures/)"
