//! Gate 8 parity test — pure-Rust runner output equals Python (`wasm-run`)
//! output, byte-for-byte.
//!
//! This is the load-bearing claim of Phase 1.5: the analytical-construction
//! transformer's specialized weights produce the same predicted-token
//! sequence under PSL's pure-Rust runner as under Transformer-VM's Python
//! / C++ inference engine. If this test passes, a sequencer or follower
//! can swap the PyO3/subprocess bridge for the in-process Rust runner
//! without changing trace_hash output.
//!
//! Golden files in `tests/golden/<primitive>.expected` were generated by
//! running the Python (`wasm-run --python --nohull`) path on the same
//! weights+input pair, then verified to be byte-identical to the Rust
//! runner's output via direct diff. See the gate-8 commit message for the
//! reproduction recipe.
//!
//! The test is `#[ignore]`-d by default because it requires the
//! `weights/<primitive>.bin` files to exist (a Tier-2 reproducibility
//! prereq — see REPRODUCE.md). To run:
//!
//!   cargo test -p psl-rust-runner --test parity --release -- --ignored

use std::path::PathBuf;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

fn run_primitive(name: &str) {
    let root = repo_root();
    let weights_path = root.join("weights").join(format!("{name}.bin"));
    let input_path = root.join("data").join(format!("{name}_spec.txt"));
    let expected_path = root
        .join("rust_runner/tests/golden")
        .join(format!("{name}.expected"));

    if !weights_path.exists() {
        panic!(
            "missing weights for {name}: {} — see REPRODUCE.md Tier 2",
            weights_path.display()
        );
    }
    if !input_path.exists() {
        panic!("missing input spec for {name}: {}", input_path.display());
    }
    if !expected_path.exists() {
        panic!(
            "missing golden file for {name}: {}",
            expected_path.display()
        );
    }

    let weights = psl_rust_runner::weights::load_weights(&weights_path)
        .unwrap_or_else(|e| panic!("loading weights {}: {e}", weights_path.display()));
    let input_str = std::fs::read_to_string(&input_path).expect("reading input spec");
    let input_owned: Vec<String> = input_str
        .split_whitespace()
        .map(|s| s.to_string())
        .collect();
    let input: Vec<&str> = input_owned.iter().map(|s| s.as_str()).collect();
    let cfg = psl_rust_runner::GenerateConfig {
        max_new_tokens: 50_000,
    };
    let predicted = psl_rust_runner::generate(&weights, &input, &cfg)
        .unwrap_or_else(|e| panic!("generating for {name}: {e}"));
    let actual = predicted.join(" ");

    let expected = std::fs::read_to_string(&expected_path).expect("reading golden");
    let expected = expected.trim();
    let actual = actual.trim();

    if actual != expected {
        // Print a short context around the first divergence to aid debugging.
        let a_toks: Vec<&str> = actual.split_whitespace().collect();
        let e_toks: Vec<&str> = expected.split_whitespace().collect();
        let mut diff_at = None;
        for i in 0..a_toks.len().min(e_toks.len()) {
            if a_toks[i] != e_toks[i] {
                diff_at = Some(i);
                break;
            }
        }
        if let Some(i) = diff_at {
            let lo = i.saturating_sub(3);
            let hi = (i + 4).min(a_toks.len().min(e_toks.len()));
            panic!(
                "{name}: divergence at token {i} (rust has {} toks, expected {}):\n  rust:     {}\n  expected: {}",
                a_toks.len(),
                e_toks.len(),
                a_toks[lo..hi].join(" "),
                e_toks[lo..hi].join(" "),
            );
        }
        panic!(
            "{name}: length mismatch: rust={} expected={}",
            a_toks.len(),
            e_toks.len()
        );
    }
}

#[test]
#[ignore]
fn parity_byte_add_with_carry() {
    run_primitive("byte_add_with_carry");
}

#[test]
#[ignore]
fn parity_byte_sub_with_borrow() {
    run_primitive("byte_sub_with_borrow");
}

#[test]
#[ignore]
fn parity_mpt_emit_record() {
    run_primitive("mpt_emit_record");
}

#[test]
#[ignore]
fn parity_freeze_apply() {
    run_primitive("freeze_apply");
}

#[test]
#[ignore]
fn parity_freeze_setup() {
    run_primitive("freeze_setup");
}
